plugins:
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  quotes: 1
  no-mixed-spaces-and-tabs: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-tabs: 0
  no-console: 0
  max-len: off
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  linebreak-style: ["error", "windows"]